### ISSUE TITLE
Rails 4.2.x and jruby compatibility

### ISSUE THREAD

**Issue by andyatkinson** [evilmartians/evil-seed#6]
Hello. In our Rails 4.2.11 app on jruby 9.2.5.0, I'm seeing the following error. I put some print statements into the refinements configuration code that back ports the `in_batches` method to `ActiveRecord::Relation` in Rails 4.2, and they print out as expected. So I'm not sure why this isn't available at runtime. This error happens on a simple usage based on the documentation, trying to navigate the first configured model's associations.

```
NoMethodError: undefined method `in_batches' for #<User::ActiveRecord_Relation:0x39352f6b>
```

Do you know if refinements work in jruby?

It appears that may not be the case, which was surprising. (still investigating) https://github.com/jruby/jruby/issues/4330

**Comment by andyatkinson** [comment]
Would `find_in_batches` in relation dumper work as a workaround?

**Comment by andyatkinson** [comment]
It seems that `find_in_batches` causes a different problem with an invalid SQL query, order by clause, so it doesn't seem like a viable workaround.

**Comment by palkan** [comment]
@andyatkinson did this work in jRuby 9.1.15.0? I've just found that there is a regression related to Refinements( My _refined_ code worked fine in 9.2.15.0, but doesn't work in 9.2.5.0 (https://travis-ci.org/palkan/anyway_config/builds/475861744) /cc @Envek

**Comment by palkan** [comment]
nvm, I found another [JRuby bug](https://github.com/jruby/jruby/issues/5550) )

**Comment by Envek** [comment]
In last 3 years JRuby has improved its Refinements support a lot. At the same time ActiveRecord 4.2 got way past its end-of-life. Closing.
